### ISSUE TITLE
 Invalid regular expression: invalid group specifier name in Safari

### ISSUE THREAD

**Issue by kzkpro** [subeshb1/Nepali-Date#22]
throws error in this line ".replace(/(?<!\\)(D{1,2}|M{1,4}|Y{2,4}|d{1,3})/g, function (match) {"

possible solution: https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

**Comment by subeshb1** [comment]
Hi, @kzkpro Thanks for reporting the issue. I will work on a fix for this.
