### ISSUE TITLE
current date issue

### ISSUE THREAD

**Issue by Paankajshah** [subeshb1/Nepali-Date#25]
is't it supposed to print the Nepali date (2077/03/11) of input `new NepaliDate(new Date(2020, 06, 25)) ` instead I am getting (2077/03/10) neither I am getting expected output of `new NepaliDate()` which is current date or am I missing something?

![output](https://user-images.githubusercontent.com/47686377/85755831-00526580-b72e-11ea-90c6-1c6e65191c01.JPG)

**Comment by subeshb1** [comment]
Hi @Paankajshah,

For the first one, 
```js
new NepaliDate(new Date(2020, 06, 25))
```

You are passing in date for the month of July whose month index is 5. The Javascript Date constructor takes (year, monthIndex, date), where the month starts from 0.
Reference from the doc: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

For the second one, 
```js
new NepaliDate()
```
The output is
```
NepaliDate {
  Symbol(Year): 2077,
  Symbol(Month): 2,
  Symbol(Date): 11,
  Symbol(Day): 4,
  Symbol(JSDate): 2020-06-24T18:15:00.000Z
}
```

This also follows the same javascript date representation where the month index is stored. So if the index is 2, the month is 3 i.e Asar.

I see the part where it gets confusing i.e the property `Symbol(Month)`. I will change it to `Symbol(MonthIndex)` in next release.


If you get confused you can always convert it to string to see the actual month and date.
```
new NepaliDate().toString()
```

**Comment by Paankajshah** [comment]
Thanks @subeshb1 I will take care of it now.
