### ISSUE TITLE
Wrong month end date value for Jestha 2081 and Ashar 2081

### ISSUE THREAD

**Issue by pabin** [subeshb1/Nepali-Date#46]

**Comment by rajbinms** [comment]
Hey! Jumping in  @pabin  with the new calendar for 2081, I see dates for Falgun (30 to 29) and Chaitra (30 to 31) for the 2081 calendar.

**Comment by subeshb1** [comment]
@pabin @rajbinms The fix has been released in v3.3.2 https://github.com/subeshb1/Nepali-Date/releases/tag/v3.3.2
