### ISSUE TITLE
Wrong Date Conversion after 14th of June 2024 (३२ ज्येष्ठ २०८१ )

### ISSUE THREAD

**Issue by s-a-j-a-g** [subeshb1/Nepali-Date#51]
Conversion shows the wrong output from the 14th of June 2024 and later dates.

Example:
new NepaliDate(new Date(2024, 5, 14)).format('YYYY/MM/DD');

  Wrong Output:  2081/03/01
  Expected Output: 2081/02/32

**Comment by Acesmndr** [comment]
@subeshb1 Need to fix this issue soon as https://chromewebstore.google.com/detail/nepali-date/jlklaielfnejdimgpfkebdnbkjagkioa?hl=en-GB also depends on it 😅

**Comment by s-a-j-a-g** [comment]
That seems to be it. I was using version `3.3.1`. Upgrading to `3.3.2` fixed the issue. Thanks!
